version: '3.3'

services:
  pangeaco-ops-geosolution:
    container_name: pangeaco-ops-geosolution
    image: pangeaco-ops-geosolution
    build: .
    ports:
      - "4033:4033"
    env_file:
      - .env